#Only in 1.16 you can use hex color like this "&#310340<player>has joined the server"

Join_enable: true
Join_message: '&e<player> &6has joined the server'

Leave_enable: true
Leave_message: '&e<player> &6has leaved the server'

Welcome_message_enable: true
Welcome_message: '&6Welcome, &e<player> &6has joined server for the first time. Have a nice day'