name: JoinMessage
version: ${project.version}
main: me.zachary.joinmessage.JoinMessage
api-version: 1.13
authors: [ Zach_FR ]
description: Custom Join/Leave message
softdepend: [PlaceholderAPI]

commands:
  joinmessagereload:
    description: Reload command
